DROP SEQUENCE TIMES_ID_SEQ;
DROP SEQUENCE JOGOS_ID_SEQ;
DROP SEQUENCE TURMAS_ID_SEQ;

ALTER TABLE JOGOS DROP CONSTRAINT JOGOS_ESCOLA_FK;
ALTER TABLE TURMAS DROP CONSTRAINT TURMAS_ESCOLA_FK;
ALTER TABLE JOGADORES DROP CONSTRAINT JOGADORES_TIME_FK;
ALTER TABLE TIMES DROP CONSTRAINT TIMES_TURMA_FK;
ALTER TABLE TIMES DROP CONSTRAINT TIMES_JOGO_FK;

DROP TABLE JOGOS;
DROP TABLE TURMAS;
DROP TABLE JOGADORES;
DROP TABLE TIMES;
DROP TABLE ESCOLAS;

CREATE TABLE ESCOLAS (
    CNPJ VARCHAR2(15) NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    NIVEL_ENSINO VARCHAR2(50) NOT NULL,
    ENDERECO VARCHAR2(255) NOT NULL,
    TELEFONE VARCHAR(20) NOT NULL
);

CREATE TABLE TURMAS (
    ID_TURMA NUMERIC NOT NULL,
    ANO VARCHAR2(10) NOT NULL,
    QUANTIDADE_ALUNOS NUMERIC(3) NOT NULL,
    CNPJ VARCHAR2(15) NOT NULL
);

CREATE TABLE JOGOS (
    ID_JOGO NUMERIC NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    CNPJ VARCHAR2(15) NOT NULL
);

CREATE TABLE TIMES (
    ID_TIME NUMERIC NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    TREINADOR VARCHAR2(255) NOT NULL,
    CATEGORIA VARCHAR2(20) NOT NULL,
    ID_TURMA NUMERIC NOT NULL,
    ID_JOGO NUMERIC NOT NULL
);

CREATE TABLE JOGADORES (
    CPF VARCHAR2(11) NOT NULL,
    NOME VARCHAR2(255) NOT NULL,
    IDADE NUMERIC(3) NOT NULL,
    POSICAO VARCHAR2(100) NOT NULL,
    NUMERO_CAMISA NUMERIC(2) NOT NULL,
    ID_TIME NUMERIC NOT NULL
);

ALTER TABLE ESCOLAS ADD PRIMARY KEY (CNPJ);
ALTER TABLE TIMES ADD PRIMARY KEY (ID_TIME);
ALTER TABLE JOGOS ADD PRIMARY KEY (ID_JOGO);
ALTER TABLE JOGADORES ADD PRIMARY KEY (CPF);
ALTER TABLE TURMAS ADD PRIMARY KEY (ID_TURMA);

ALTER TABLE JOGOS ADD CONSTRAINT JOGOS_ESCOLA_FK
FOREIGN KEY (CNPJ)
REFERENCES ESCOLAS (CNPJ);

ALTER TABLE TURMAS ADD CONSTRAINT TURMAS_ESCOLA_FK
FOREIGN KEY (CNPJ)
REFERENCES ESCOLAS (CNPJ);

ALTER TABLE TIMES ADD CONSTRAINT TIMES_TURMA_FK
FOREIGN KEY (ID_TURMA)
REFERENCES TURMAS (ID_TURMA);

ALTER TABLE TIMES ADD CONSTRAINT TIMES_JOGO_FK
FOREIGN KEY (ID_JOGO)
REFERENCES JOGOS (ID_JOGO);

ALTER TABLE JOGADORES ADD CONSTRAINT JOGADORES_TIME_FK
FOREIGN KEY (ID_TIME)
REFERENCES TIMES (ID_TIME);

CREATE SEQUENCE TIMES_ID_SEQ;
CREATE SEQUENCE JOGOS_ID_SEQ;
CREATE SEQUENCE TURMAS_ID_SEQ;